name: Build
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.0
      id: checkout_code
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      id: setup_msbuild
      
    - name: Restore or install vcpkg
      uses: lukka/run-vcpkg@v7
      with:
        setupOnly: true
        vcpkgGitCommitId: 2a0c48a32dc82fe4416605fae8ac897bc2dab4da

    - name: Install vcpkg integration
      run: |
        vcpkg update
        vcpkg integrate install
        
    - name: Install OpenCV [world]
      run: vcpkg install opencv3[world]:x64-windows 

    - name: Clear vcpkg downloads
      shell: powershell
      run: |
        Remove-Item -LiteralPath "vcpkg/buildtrees" -Force -Recurse -ErrorAction Ignore
        Remove-Item -LiteralPath "vcpkg/downloads" -Force -Recurse -ErrorAction Ignore
      
    - name: Install Boost
      run: vcpkg install boost:x64-windows
      
    - name: Clear vcpkg downloads
      shell: powershell
      run: |
        Remove-Item -LiteralPath "vcpkg/buildtrees" -Force -Recurse -ErrorAction Ignore
        Remove-Item -LiteralPath "vcpkg/downloads" -Force -Recurse -ErrorAction Ignore
      
    - name : Install [glm, curlpp, cereal]
      run : vcpkg install glm:x64-windows curlpp:x64-windows cereal:x64-windows
      
    - name : Install [sfml, glew]
      run : vcpkg install sfml:x64-windows glew:x64-windows

    - name: Clear vcpkg downloads
      shell: powershell
      run: |
        Remove-Item -LiteralPath "vcpkg/buildtrees" -Force -Recurse -ErrorAction Ignore
        Remove-Item -LiteralPath "vcpkg/downloads" -Force -Recurse -ErrorAction Ignore

    - name : Setup Glog
      run : |
        git clone https://github.com/google/glog.git external/glog
        cd external/glog
        git reset --hard f8c8e99fdfb998c2ba96cfb470decccf418f0b30
        mkdir vcbuild; cd vcbuild
        cmake -DBUILD_SHARED_LIBS=ON ..
        msbuild glog.vcxproj "/p:Configuration=Release;Platform=x64;WindowsTargetPlatformVersion=10.0"

    - name : Setup GFlags
      run : |
        git clone https://github.com/gflags/gflags.git external/gflags
        cd external/gflags
        git reset --hard 827c769e5fc98e0f2a34c47cef953cc6328abced
        mkdir vcbuild; cd vcbuild
        cmake -DBUILD_SHARED_LIBS=ON ..
        msbuild gflags.vcxproj "/p:Configuration=Release;Platform=x64;WindowsTargetPlatformVersion=10.0"

    - name: Install Kinect SDKs
      run: |
        vcpkg install kinectsdk1:x64-windows 
        vcpkg install kinectsdk2:x64-windows 
      
    - name: Setup non-vcpkg dependencies
      run: |
        git clone https://github.com/ValveSoftware/openvr.git/ external/openvr
        git clone https://gitlab.com/libeigen/eigen.git/ external/eigen
        git clone https://github.com/g-truc/glm external/glm
        git clone https://github.com/KimihikoAkayasaki/SFGUI external/SFGUI

    - name: Fix min/max error in GLM
      run: sed -i '/#include <limits>/c\#include <limits>\n\n#undef min\n#undef max' external/glm/glm/gtx/component_wise.inl

    - name: Setup and build SFGUI
      run: |
        cd external/SFGUI
        mkdir build
        cd build
        cmake "-DBUILD_SHARED_LIBS=ON -DCMAKE_TOOLCHAIN_FILE=D:/a/KinectToVR/KinectToVR/vcpkg/scripts/buildsystems/vcpkg.cmake" ..
        msbuild SFGUI.vcxproj "/p:Configuration=Release;Platform=x64;WindowsTargetPlatformVersion=10.0"

    - name: Clone and setup K2APP
      shell: powershell
      run: |
        git clone https://github.com/KinectToVR/k2vr-application external/KTVR
        New-Item -ItemType Junction -Path external/KTVR/external/openvr -Target external/openvr
        New-Item -ItemType Junction -Path external/KTVR/external/eigen -Target external/eigen
        New-Item -ItemType Junction -Path external/KTVR/external/glm -Target external/glm
        New-Item -ItemType Junction -Path external/KTVR/external/glog -Target external/glog
        New-Item -ItemType Junction -Path external/KTVR/external/gflags -Target external/gflags

    - name: Build K2API and K2APP's driver
      run: |
        cd external/KTVR
        msbuild "/t:KinectToVR_API" "/p:Configuration=Release;Platform=x64;WindowsTargetPlatformVersion=10.0"
        msbuild "/t:Driver_KinectToVR" "/p:Configuration=Release;Platform=x64;WindowsTargetPlatformVersion=10.0"
        
    - name: Remove Kinect library links
      run: |
          sed -i -e 's/Kinect10.lib//g' KinectV1Process/KinectV1Process.vcxproj
          sed -i -e 's/Kinect20.lib//g' KinectV2Process/KinectV2Process.vcxproj
          sed -i -e 's/Kinect10.lib//g' KV1CrashHandler/KV1CrashHandler.vcxproj
          sed -i -e 's/Kinect20.lib//g' KV2CrashHandler/KV2CrashHandler.vcxproj

    - name: Build KinectToVR
      id: run_msbuild_k2vr
      run: msbuild "/p:Configuration=Release;Platform=x64;WindowsTargetPlatformVersion=10.0"

    - name: Clear Release folder
      shell: powershell
      run: |
        cd x64/Release
        Get-ChildItem *.pdb | foreach { Remove-Item -Path $_.FullName }
        Get-ChildItem *.exp | foreach { Remove-Item -Path $_.FullName }
        Get-ChildItem *.lib | foreach { Remove-Item -Path $_.FullName }

    - name: Get short commit SHA
      id: slug
      run: "$slug = '::set-output name=slug::' + $env:GITHUB_SHA.SubString(0,7); echo $slug"

    - name: Upload K2EX Release artifact
      uses: actions/upload-artifact@v2
      with:
        name: K2EX-Release-${{ steps.slug.outputs.slug }}
        path: x64/Release/
        if-no-files-found: error

    - name: Upload K2Driver Release artifact
      uses: actions/upload-artifact@v2
      with:
        name: K2Driver-Release-${{ steps.slug.outputs.slug }}
        path: external/KTVR/x64/Release/driver/
        if-no-files-found: error
